export const PIECES_UPDATE = "PIECES_UPDATE";
export const UPDATE_BOARD = "UPDATE_BOARD";
export const USER_CONFIGURATION = "USER_CONFIGURATION";
export const SET_HINTS_VISIBILITY = "SET_HINTS_VISIBILITY";
export const SET_PUZZLE_SIZE = "SET_PUZZLE_SIZE";
