export const PIECES_UPDATE = "PIECES_UPDATE";
export const MOVE_ACTIVE = "MOVE_ACTIVE";
export const USER_CONFIGURATION = "USER_CONFIGURATION";
export const SET_HINTS_VISIBILITY = "SET_HINTS_VISIBILITY";
export const SET_PUZZLE_SIZE = "SET_PUZZLE_SIZE";
